language: java

jdk:
  - openjdk11

env:
  global:
    - NUODB_HOME=/opt/nuodb
    - NUODB_INCLUDE_DIR=/opt/nuodb/include
    - NUODB_LIB_DIR=/opt/nuodb/lib64
    - TZ=America/New_York
    - NUO_VERSION=4.0.1.1

notifications:
  recipients:
    - drivers@nuodb.com

before_install:
  - ./bin/nuodb/nuodb_setup.sh

install:
  - true

script:
  - cmake -G "Unix Makefiles" -DDBMS=nuodb -DCMAKE_INSTALL_PREFIX:PATH=/opt/local/dbt -DCMAKE_BUILD_TYPE=Debug -DNUODB_INCLUDE_DIR=${NUODB_INCLUDE_DIR}
  - sudo make package install

after_script:
  - sudo dpkg -r nuodb
